name = "cella-backend"
compatibility_date = "2024-11-06"
main = "./src/entry.ts"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
NODE_ENV = "development"
PGLITE = false
DATABASE_URL = "postgres://postgres:postgres@0.0.0.0:5432/postgres"
UNSUBSCRIBE_TOKEN_SECRET = "some_secret_token"
ARGON_SECRET = "argon_two_secret"
REMOTE_SYSTEM_ACCESS_IP = "*" 

# [[kv_namespaces]]
# binding = "KV_NAMESPACE"
# id = "1234"

# [[r2_buckets]]
# binding = "BUCKET_NAME"
# bucket_name = "bucket-name"

# [[d1_databases]]
# binding = "DB"
# database_name = "database-namer"
# database_id = ""

# [ai]
# binding = "AI"
